// NOTELIST 
export const NOTE_LIST_REQUEST = "NOTE_LIST_REQUEST";
export const NOTE_LIST_SUCCESS = "NOTE_LIST_SUCCESS";
export const NOTE_LIST_FAIL = "NOTE_LIST_FAIL";

// MEMBUAT CONSTANT TERLEBIH DAHULU 
// CREATE NOTE 
export const NOTE_CREATE_REQUEST = "NOTE_CREATE_REQUEST"
export const NOTE_CREATE_SUCCESS = "NOTE_CREATE_SUCCESS"
export const NOTE_CREATE_FAIL = "NOTE_CREATE_FAIL"

// UPDATE NOTE 
export const NOTE_UPDATE_REQUEST = "NOTES_UPDATE_REQUEST";
export const NOTE_UPDATE_SUCCESS = "NOTES_UPDATE_SUCCESS";
export const NOTE_UPDATE_FAIL = "NOTES_UPDATE_FAIL";

// DELETE NOTE
export const NOTE_DELETE_REQUEST = "NOTES_DELETE_REQUEST";
export const NOTE_DELETE_SUCCESS = "NOTES_DELETE_SUCCESS";
export const NOTE_DELETE_FAIL = "NOTES_DELETE_FAIL";
